services:
  pipeline:
    image: playsmartbuas/bg-app-pipeline
    container_name: app-pipeline
    volumes:
      - C:/Users/breda/Documents/esports:/mnt/raid0/esports
    environment:
      - TZ=Europe/Amsterdam
    restart: unless-stopped

  sftp:
    image: atmoz/sftp
    container_name: app-sftp-container
    ports:
      - "2422:22"
    volumes:
      - C:/esports/sftp_data:/home/localhost/data
    environment:
      - SFTP_USERS=localhost:yourpassword:1234
    restart: unless-stopped
    command: >
      /bin/sh -c "mkdir -p /home/localhost/data/emotion &&
      mkdir -p /home/localhost/data/video &&
      mkdir -p /home/localhost/data/input &&
      mkdir -p /home/localhost/data/merged &&
      mkdir -p /home/localhost/data/gaze &&
      mkdir -p /home/localhost/data/eda &&
      mkdir -p /home/localhost/data/audio &&
      chown -R 1234:100 /home/localhost/data &&
      chmod -R 775 /home/localhost/data &&
      /usr/sbin/sshd -D"


#       PS C:\WINDOWS\system32> New-NetFirewallRule -DisplayName "SFTP Docker" -Direction Inbound -Protocol TCP -LocalPort 2422 -Action Allow


# Name                          : {63dc8782-76ee-411a-87ce-81d3ef2de6ae}
# DisplayName                   : SFTP Docker
# Description                   :
# DisplayGroup                  :
# Group                         :
# Enabled                       : True
# Profile                       : Any
# Platform                      : {}
# Direction                     : Inbound
# Action                        : Allow
# EdgeTraversalPolicy           : Block
# LooseSourceMapping            : False
# LocalOnlyMapping              : False
# Owner                         :
# PrimaryStatus                 : OK
# Status                        : The rule was parsed successfully from the store. (65536)
# EnforcementStatus             : NotApplicable
# PolicyStoreSource             : PersistentStore
# PolicyStoreSourceType         : Local
# RemoteDynamicKeywordAddresses : {}
# PolicyAppId                   :
# PackageFamilyName             :
