services:
  pipeline:
    image: playsmartbuas/bg-app-pipeline
    container_name: app-pipeline
    volumes:
      - C:/Users/breda/Documents/esports:/mnt/raid0/esports
    environment:
      - TZ=Europe/Amsterdam
    restart: unless-stopped

  sftp:
    image: atmoz/sftp
    container_name: app-sftp-container
    ports:
      - "2422:22"
    volumes:
      - C:/esports/sftp_data:/home/localhost/data
    environment:
      - SFTP_USERS=localhost:yourpassword:1234
    restart: unless-stopped
    command: >
      /bin/sh -c "mkdir -p /home/localhost/data/emotion &&
      mkdir -p /home/localhost/data/video &&
      mkdir -p /home/localhost/data/input &&
      mkdir -p /home/localhost/data/merged &&
      mkdir -p /home/localhost/data/gaze &&
      mkdir -p /home/localhost/data/eda &&
      mkdir -p /home/localhost/data/audio &&
      chown -R 1234:100 /home/localhost/data &&
      chmod -R 775 /home/localhost/data &&
      /usr/sbin/sshd -D"


#    Connection-specific DNS Suffix  . :
#    Link-local IPv6 Address . . . . . : fe80::1780:1e01:9e77:b50b%11
#    IPv4 Address. . . . . . . . . . . : 192.168.0.101
#    Subnet Mask . . . . . . . . . . . : 255.255.255.0
#    Default Gateway . . . . . . . . . : 192.168.0.1

# Ethernet adapter Bluetooth Network Connection:

#    Media State . . . . . . . . . . . : Media disconnected
#    Connection-specific DNS Suffix  . :

# Ethernet adapter vEthernet (WSL (Hyper-V firewall)):

#    Connection-specific DNS Suffix  . :
#    Link-local IPv6 Address . . . . . : fe80::42f:1ba2:b18e:d675%34
#    IPv4 Address. . . . . . . . . . . : 192.168.16.1
#    Subnet Mask . . . . . . . . . . . : 255.255.240.0
#    Default Gateway . . . . . . . . . :
